package report

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/juparave/codereviewer/internal/domain"
)

// Formatter generates Markdown reports
type Formatter struct {
	outputDir string
}

// NewFormatter creates a new Formatter
func NewFormatter(outputDir string) *Formatter {
	return &Formatter{outputDir: outputDir}
}

// Write generates and saves a Markdown report
func (f *Formatter) Write(report *domain.Report) (string, error) {
	// Ensure output directory exists
	if err := os.MkdirAll(f.outputDir, 0755); err != nil {
		return "", fmt.Errorf("creating output directory: %w", err)
	}

	// Generate filename
	filename := report.Date.Format("2006-01-02") + ".md"
	filepath := filepath.Join(f.outputDir, filename)

	// Generate content
	content := f.format(report)

	// Write file
	if err := os.WriteFile(filepath, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("writing report: %w", err)
	}

	return filepath, nil
}

func (f *Formatter) format(report *domain.Report) string {
	var sb strings.Builder

	// Header
	sb.WriteString(fmt.Sprintf("# Code Review Report - %s\n\n", report.Date.Format("January 2, 2006")))

	// Summary
	sb.WriteString("## Summary\n\n")
	sb.WriteString(report.Summary)
	sb.WriteString("\n\n")

	// Stats
	if report.CommitCount > 0 {
		sb.WriteString(fmt.Sprintf("**Reviewed:** %d commits across %d files in %d repositories\n\n",
			report.CommitCount, report.FileCount, len(report.Repositories)))
	}

	// No findings case
	if !report.HasFindings() {
		sb.WriteString("✅ **No issues found.** Great work!\n")
		return sb.String()
	}

	// Findings count by severity
	sb.WriteString(fmt.Sprintf("**Findings:** %d total (%d High, %d Medium, %d Low)\n\n",
		report.TotalFindings(), report.HighCount(), report.MediumCount(), report.LowCount()))

	// Findings grouped by severity
	sb.WriteString("---\n\n")
	sb.WriteString("## Findings\n\n")

	// High severity first
	for _, finding := range report.Findings {
		if finding.Severity == domain.SeverityHigh {
			f.writeFinding(&sb, finding)
		}
	}

	// Medium severity
	for _, finding := range report.Findings {
		if finding.Severity == domain.SeverityMedium {
			f.writeFinding(&sb, finding)
		}
	}

	// Low severity
	for _, finding := range report.Findings {
		if finding.Severity == domain.SeverityLow {
			f.writeFinding(&sb, finding)
		}
	}

	// Footer
	sb.WriteString("---\n\n")
	sb.WriteString(fmt.Sprintf("*Generated by Code Review Agent at %s*\n",
		time.Now().Format("15:04 MST")))

	return sb.String()
}

func (f *Formatter) writeFinding(sb *strings.Builder, finding domain.Finding) {
	// Severity badge
	var badge string
	switch finding.Severity {
	case domain.SeverityHigh:
		badge = "🔴"
	case domain.SeverityMedium:
		badge = "🟡"
	case domain.SeverityLow:
		badge = "🟢"
	}

	sb.WriteString(fmt.Sprintf("### %s %s\n\n", badge, finding.Title))
	sb.WriteString(fmt.Sprintf("**Severity:** %s | **Repository:** %s\n\n", finding.Severity, finding.RepoName))

	if len(finding.Files) > 0 {
		sb.WriteString("**Files:**\n")
		for _, file := range finding.Files {
			sb.WriteString(fmt.Sprintf("- `%s`\n", file))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("**Issue:**\n")
	sb.WriteString(finding.Explanation)
	sb.WriteString("\n\n")

	sb.WriteString("**Suggested Action:**\n")
	sb.WriteString(finding.Action)
	sb.WriteString("\n\n")
}

// ToHTML converts markdown report content to basic HTML for email
func (f *Formatter) ToHTML(report *domain.Report) string {
	// Simple HTML version for email
	var sb strings.Builder

	sb.WriteString("<!DOCTYPE html>\n<html>\n<head>\n")
	sb.WriteString("<style>\n")
	sb.WriteString("body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }\n")
	sb.WriteString("h1 { color: #1a1a1a; border-bottom: 2px solid #667eea; padding-bottom: 10px; }\n")
	sb.WriteString("h3 { margin-top: 24px; }\n")
	sb.WriteString(".high { color: #dc2626; }\n")
	sb.WriteString(".medium { color: #d97706; }\n")
	sb.WriteString(".low { color: #059669; }\n")
	sb.WriteString(".finding { background: #f9fafb; border-left: 4px solid #667eea; padding: 16px; margin: 16px 0; }\n")
	sb.WriteString(".finding-high { border-left-color: #dc2626; }\n")
	sb.WriteString(".finding-medium { border-left-color: #d97706; }\n")
	sb.WriteString(".finding-low { border-left-color: #059669; }\n")
	sb.WriteString("code { background: #f3f4f6; padding: 2px 6px; border-radius: 4px; font-size: 14px; }\n")
	sb.WriteString("</style>\n</head>\n<body>\n")

	sb.WriteString(fmt.Sprintf("<h1>Code Review Report - %s</h1>\n", report.Date.Format("January 2, 2006")))
	sb.WriteString(fmt.Sprintf("<p>%s</p>\n", report.Summary))

	if report.CommitCount > 0 {
		sb.WriteString(fmt.Sprintf("<p><strong>Reviewed:</strong> %d commits across %d files in %d repositories</p>\n",
			report.CommitCount, report.FileCount, len(report.Repositories)))
	}

	if !report.HasFindings() {
		sb.WriteString("<p>✅ <strong>No issues found.</strong> Great work!</p>\n")
	} else {
		sb.WriteString(fmt.Sprintf("<p><strong>Findings:</strong> %d total (<span class='high'>%d High</span>, <span class='medium'>%d Medium</span>, <span class='low'>%d Low</span>)</p>\n",
			report.TotalFindings(), report.HighCount(), report.MediumCount(), report.LowCount()))

		for _, finding := range report.Findings {
			severityClass := strings.ToLower(string(finding.Severity))
			sb.WriteString(fmt.Sprintf("<div class='finding finding-%s'>\n", severityClass))
			sb.WriteString(fmt.Sprintf("<h3>%s</h3>\n", finding.Title))
			sb.WriteString(fmt.Sprintf("<p><strong>Severity:</strong> <span class='%s'>%s</span> | <strong>Repository:</strong> %s</p>\n",
				severityClass, finding.Severity, finding.RepoName))

			if len(finding.Files) > 0 {
				sb.WriteString("<p><strong>Files:</strong> ")
				for i, file := range finding.Files {
					if i > 0 {
						sb.WriteString(", ")
					}
					sb.WriteString(fmt.Sprintf("<code>%s</code>", file))
				}
				sb.WriteString("</p>\n")
			}

			sb.WriteString(fmt.Sprintf("<p><strong>Issue:</strong> %s</p>\n", finding.Explanation))
			sb.WriteString(fmt.Sprintf("<p><strong>Suggested Action:</strong> %s</p>\n", finding.Action))
			sb.WriteString("</div>\n")
		}
	}

	sb.WriteString(fmt.Sprintf("<p style='color: #6b7280; font-size: 12px; margin-top: 40px;'>Generated by Code Review Agent at %s</p>\n",
		time.Now().Format("15:04 MST")))
	sb.WriteString("</body>\n</html>")

	return sb.String()
}
